### ISSUE TITLE
NullPointerException if working as a service

### ISSUE THREAD

**Issue by hvorragend** [peterkappelt/Tradfri-FHEM#13]
Exception at readline function:

Exception in thread "main" java.lang.NullPointerException
	at net.kappelt.JTradfri.Commands.Commandline.run(Commandline.java:26)
	at net.kappelt.JTradfri.JTradfri.startThreadHandler(JTradfri.java:62)
	at net.kappelt.JTradfri.JTradfri.main(JTradfri.java:48)

**Comment by peterkappelt** [comment]
Strange. Do you run JTradfri as a systemd service (please show your config than) or in another way?

**Comment by dg7pc** [comment]
Same here, took me a while to get this simple Unit file working. Initially I added some redirections into a logfile which failed. 

Unit file:
```
#
[Unit]
Description=JTradfri FHEM Gateway

[Service]
WorkingDirectory=/opt/fhem-add-ons/
User=fhem

ExecStart=/opt/java8/current/bin/java -server -jar /opt/fhem-add-ons/JTradfri-06112017-0.0.5-snapshot-all.jar -s PSK  -g GW-IP

[Install]
WantedBy=multi-user.target
#http://electronic.kappelt.net/wordpress/de/ikea-tradfri-module-for-fhem-beta/

```

journalctl shows:
```
Jan 16 22:17:55 clio4 systemd[1]: Starting JTradfri FHEM Gateway...
Jan 16 22:17:55 clio4 systemd[1]: Started JTradfri FHEM Gateway.
Jan 16 22:17:56 clio4 java[29342]: JTradfri 0.0.5-snapshot
Jan 16 22:17:56 clio4 java[29342]: [GWConnection] Doing handshake to get connection keys/ parameters...
Jan 16 22:17:56 clio4 java[29342]: Jan 16, 2018 10:17:56 PM org.eclipse.californium.core.network.CoapEndpoint start
Jan 16 22:17:56 clio4 java[29342]: INFORMATION: Starting endpoint at coaps://0.0.0.0:0
Jan 16 22:17:56 clio4 java[29342]: Jan 16, 2018 10:17:56 PM org.eclipse.californium.scandium.DTLSConnector start
Jan 16 22:17:56 clio4 java[29342]: INFORMATION: DTLS connector listening on [0.0.0.0/0.0.0.0:41930] with MTU [1.280] using (inbound) datagram buffer size [16.474 bytes
Jan 16 22:17:56 clio4 java[29342]: Jan 16, 2018 10:17:56 PM org.eclipse.californium.core.network.CoapEndpoint start
Jan 16 22:17:56 clio4 java[29342]: INFORMATION: Started endpoint at coaps://0.0.0.0:41930
Jan 16 22:17:56 clio4 java[29342]: Jan 16, 2018 10:17:56 PM org.eclipse.californium.core.CoapClient setEndpoint
Jan 16 22:17:56 clio4 java[29342]: INFORMATION: Started set client endpoint 0.0.0.0/0.0.0.0:41930
Jan 16 22:17:56 clio4 java[29342]: [GWConnection] Handshake: Using identity "X"
Jan 16 22:17:57 clio4 java[29342]: [GWConnection] Tradfri gateway firmware version: 1.3.0014
Jan 16 22:17:57 clio4 java[29342]: [GWConnection] Got connection psk: Y
Jan 16 22:17:57 clio4 java[29342]: Jan 16, 2018 10:17:57 PM org.eclipse.californium.scandium.DTLSConnector stop
Jan 16 22:17:57 clio4 java[29342]: INFORMATION: Stopping DTLS connector on [0.0.0.0/0.0.0.0:41930]
Jan 16 22:17:57 clio4 java[29342]: Jan 16, 2018 10:17:57 PM org.eclipse.californium.core.network.CoapEndpoint start
Jan 16 22:17:57 clio4 java[29342]: INFORMATION: Starting endpoint at coaps://0.0.0.0:0
Jan 16 22:17:57 clio4 java[29342]: Jan 16, 2018 10:17:57 PM org.eclipse.californium.scandium.DTLSConnector start
Jan 16 22:17:57 clio4 java[29342]: INFORMATION: DTLS connector listening on [0.0.0.0/0.0.0.0:57629] with MTU [1.280] using (inbound) datagram buffer size [16.474 bytes
Jan 16 22:17:57 clio4 java[29342]: Jan 16, 2018 10:17:57 PM org.eclipse.californium.core.network.CoapEndpoint start
Jan 16 22:17:57 clio4 java[29342]: INFORMATION: Started endpoint at coaps://0.0.0.0:57629
Jan 16 22:17:57 clio4 java[29342]: Jan 16, 2018 10:17:57 PM org.eclipse.californium.core.CoapClient setEndpoint
Jan 16 22:17:57 clio4 java[29342]: INFORMATION: Started set client endpoint 0.0.0.0/0.0.0.0:57629
Jan 16 22:17:57 clio4 java[29342]: [GWConnection] Fetching well-known...
Jan 16 22:17:57 clio4 java[29342]: [GWConnection] <//15006>;ct=0;obs,<//15001>;ct=0;obs,<//15004>;ct=0;obs,<//15004/add>;ct=0,<//15004/remove>;ct=0,<//15010>;ct=0;obs,
Jan 16 22:17:57 clio4 java[29342]: JTradfri Commandline
Jan 16 22:17:57 clio4 java[29342]: Type "help" to show available commands
Jan 16 22:17:57 clio4 java[29342]: Exception in thread "main" java.lang.NullPointerException
Jan 16 22:17:57 clio4 java[29342]: at net.kappelt.JTradfri.Commands.Commandline.run(Commandline.java:26)
Jan 16 22:17:57 clio4 java[29342]: at net.kappelt.JTradfri.JTradfri.startThreadHandler(JTradfri.java:62)
Jan 16 22:17:57 clio4 java[29342]: at net.kappelt.JTradfri.JTradfri.main(JTradfri.java:48)
Jan 16 22:17:57 clio4 java[29342]: [TcpServer] Binding of socket @ port 1505 successfull.
Jan 16 22:18:49 clio4 java[29342]: [TcpServer] Connection at port 1505 opened (Hash 1122061385)
Jan 16 22:18:49 clio4 java[29342]: [TcpClientHandler-1122061385] Received command: device::subscribe::65537

```

**Comment by peterkappelt** [comment]
But it seems to be OK after that Exception. Does it work afterwards? The lines below the Exception state, that FHEM hast connected to JTradfri and is listening for new Data.

So is that a serious issue or a thing of beauty?

**Comment by dg7pc** [comment]
Looks like a beauty thing for one of the next releases.

**Comment by peterkappelt** [comment]
Should be fixed, if you append "--no-commandline" as an command line parameter and use the newest version of JTradfri.

Feedback is appreciated. Please close this issue, if the problem was resolved.

Explanation: JTradfri provides a dynamic command line input, you can execute commands if JTradfri runs in the foreground. Thus, it reads lines from STDIN. I suppose that STDIN doesn't exist (?) while running as a Systemd-Service

**Comment by dg7pc** [comment]
Works for me.
I also switched from jar download to git pull, makes updates easier.

As I did not open the issue, I am unsure if I can close it. Lets wait for @hvorragend

**Comment by cmile** [comment]
works for me, too
